---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---


# load libraries and datasets

```{r setup, message= FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("instacart")
```


# Plotly plots

## Scatterplots

```{r message = FALSE}
instacart %>% 
  select(order_id, product_id, order_hour_of_day, product_name, aisle) %>%
  filter(aisle == "fresh fruits") %>% 
  group_by(order_hour_of_day, product_name) %>% 
  summarize(number_of_orders = n()) %>%
  filter(number_of_orders > 100) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~number_of_orders, color = ~product_name, text = ~product_name,
    alpha = 0.8, type = "scatter", mode = "markers", colors = "viridis")
```


## Boxplot


```{r}
instacart %>% 
  select(aisle, product_name, order_hour_of_day) %>%
  filter(aisle == "frozen juice") %>%
  mutate(product_name = fct_reorder(product_name, order_hour_of_day)) %>% 
  plot_ly(x = ~product_name, y = ~order_hour_of_day, color = ~product_name,
          type = "box", colors = "viridis") %>%
  layout(showlegend = TRUE, legend = list(font = list(size = 8)))
```


## Bar plot

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 15000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle,
          type = "bar", colors = "viridis")
```


